In [1]:
import numpy as np
import pandas as pd
import statistics

In [2]:
df = pd.read_excel('RatingTable.xlsx')

In [3]:
df.head()

,Sno,Difficulty level,Question,Actual Answer,ChatGPT Answer,Accuracy (1-6): Rating1,Completeness(1-3): Rating1
0,1,Moderate,A higher-level programming language cannot ins...,TRUE.This is the reason that a big or expensiv...,FALSE.A higher-level programming language can ...,2,1
1,2,Easy,How many ISAs are normally implemented by a si...,One,A single microarchitecture typically implement...,6,3
2,3,Moderate,"There are two kinds of programming languages, ...",High-level and low-level lanugages,There are two broad categories of programming ...,6,3
3,4,Easy,There are 52 weeks in a year on the Gregorian ...,6 bits,The least number of bits needed to represent 5...,6,3
4,5,Moderate,An office building has 12 rooms on each floor ...,Total number of rooms: 12 * 9 = 108 rooms tot...,"To address each room in the office building, w...",6,3

In [4]:
set1 = df['Accuracy (1-6): Rating1']
set2 = df['Completeness(1-3): Rating1']
median_acc = df['Accuracy (1-6): Rating1'].median()
median_com = df['Completeness(1-3): Rating1'].median()
mean_acc = round(df['Accuracy (1-6): Rating1'].mean(),2)
mean_com = round(df['Completeness(1-3): Rating1'].mean(),2)
mode_acc = statistics.mode(set1)
mode_com = statistics.mode(set2)
std_acc = round(df['Accuracy (1-6): Rating1'].std(), 2)
std_com = round(df['Completeness(1-3): Rating1'].std(), 2)
acc_q3, acc_q1 = np.percentile(df['Accuracy (1-6): Rating1'], [75 ,25])
iqr_acc = acc_q3 - acc_q1
com_q3, com_q1 = np.percentile(df['Completeness(1-3): Rating1'], [75 ,25])
iqr_com = com_q3 - com_q1
print('***************ACCURACY**************')
print('Median Accuracy:', median_acc)
print('Mean Accuracy:', mean_acc)
print('Mode Accuracy:', mode_acc)
print('SD Accuracy:', std_acc)
print('IQR Accuracy:', iqr_acc)
print('*************COMPLETENESS************')
print('Median Completeness:', median_com)

print('Mean Completeness:', mean_com)

print('Mode Completeness:', mode_com)

print('SD Completeness:', std_com)

print('IQR Completeness:', iqr_com)

***************ACCURACY**************
Median Accuracy: 6.0
Mean Accuracy: 4.59
Mode Accuracy: 6
SD Accuracy: 1.71
IQR Accuracy: 3.0
*************COMPLETENESS************
Median Completeness: 3.0
Mean Completeness: 2.53
Mode Completeness: 3
SD Completeness: 0.78
IQR Completeness: 1.0

In [5]:
# x = ['','','','','','','Median','Mean','Mode', 'SD']
x = [1, 2, 3, 4, 5, 6]
y = ['Accuracy(1-6)','Count of Accuracy','%Accuracy']
row_list = x
col_list = y
total = 58
df_total = pd.DataFrame('',[],col_list)
df_total['Accuracy(1-6)'] = x
df_total.set_index('Accuracy(1-6)', drop = True)
# df_total.loc['Accuracy(1-6)'] = 
# df_total.loc['']['Accuracy(1-6)'] = 2
# df_total.loc['']['Accuracy(1-6)'] = 3
# df_total.loc['']['Accuracy(1-6)'] = 4
# df_total.loc['']['Accuracy(1-6)'] = 5
# df_total.loc['']['Accuracy(1-6)'] = 6
df_total.loc[0,'Count of Accuracy'] = 0
df_total.loc[1,'Count of Accuracy'] = df['Accuracy (1-6): Rating1'].value_counts()[2]
df_total.loc[2,'Count of Accuracy'] = df['Accuracy (1-6): Rating1'].value_counts()[3]
df_total.loc[3,'Count of Accuracy'] = df['Accuracy (1-6): Rating1'].value_counts()[4]
df_total.loc[4,'Count of Accuracy'] = df['Accuracy (1-6): Rating1'].value_counts()[5]
df_total.loc[5,'Count of Accuracy'] = df['Accuracy (1-6): Rating1'].value_counts()[6]

# df_total.loc['Median']['Accuracy'] = df['Accuracy (1-6): Rating1'].median()

# df_total.loc['Mean']['Accuracy'] = round(df['Accuracy (1-6): Rating1'].mean(), 2)

# df_total.loc['Mode']['Accuracy'] = statistics.mode(df['Accuracy (1-6): Rating1'])

# df_total.loc['SD']['Accuracy'] = round(df['Accuracy (1-6): Rating1'].std(), 2)


df_total.loc[0,'%Accuracy'] = 0
df_total.loc[1,'%Accuracy'] = round((df_total.loc[1,'Count of Accuracy']/total)*100, 2)
df_total.loc[2,'%Accuracy'] = round((df_total.loc[2,'Count of Accuracy']/total)*100, 2)
df_total.loc[3,'%Accuracy'] = round((df_total.loc[3,'Count of Accuracy']/total)*100, 2)
df_total.loc[4,'%Accuracy'] = round((df_total.loc[4,'Count of Accuracy']/total)*100, 2)
df_total.loc[5,'%Accuracy'] = round((df_total.loc[5,'Count of Accuracy']/total)*100, 2)


df_total

   Accuracy(1-6) Count of Accuracy %Accuracy
0              1                 0         0
1              2                13     22.41
2              3                 6     10.34
3              4                 4       6.9
4              5                 4       6.9
5              6                31     53.45

In [6]:
x = [1, 2, 3]
y = ['Completeness(1-3)','Count of Completeness','%Completeness']
row_list = x
col_list = y
total = 58
df_total = pd.DataFrame('',[],col_list)
df_total['Completeness(1-3)'] = x
df_total.set_index('Completeness(1-3)', drop = True)
# df_total.loc['Accuracy(1-6)'] = 
# df_total.loc['']['Accuracy(1-6)'] = 2
# df_total.loc['']['Accuracy(1-6)'] = 3
# df_total.loc['']['Accuracy(1-6)'] = 4
# df_total.loc['']['Accuracy(1-6)'] = 5
# df_total.loc['']['Accuracy(1-6)'] = 6
df_total.loc[0,'Count of Completeness'] = df['Completeness(1-3): Rating1'].value_counts()[1]
df_total.loc[1,'Count of Completeness'] = df['Completeness(1-3): Rating1'].value_counts()[2]
df_total.loc[2,'Count of Completeness'] = df['Completeness(1-3): Rating1'].value_counts()[3]


# df_total.loc['Median']['Accuracy'] = df['Accuracy (1-6): Rating1'].median()

# df_total.loc['Mean']['Accuracy'] = round(df['Accuracy (1-6): Rating1'].mean(), 2)

# df_total.loc['Mode']['Accuracy'] = statistics.mode(df['Accuracy (1-6): Rating1'])

# df_total.loc['SD']['Accuracy'] = round(df['Accuracy (1-6): Rating1'].std(), 2)


df_total.loc[0,'%Completeness'] = round((df_total.loc[0,'Count of Completeness']/total)*100, 2)
df_total.loc[1,'%Completeness'] = round((df_total.loc[1,'Count of Completeness']/total)*100, 2)
df_total.loc[2,'%Completeness'] = round((df_total.loc[2,'Count of Completeness']/total)*100, 2)


df_total

   Completeness(1-3) Count of Completeness %Completeness
0                  1                    10         17.24
1                  2                     7         12.07
2                  3                    41         70.69

In [8]:
# Correlation 
from scipy.stats import spearmanr
 
# sample data
x = df['Accuracy (1-6): Rating1']
y = df['Completeness(1-3): Rating1']
 
# calculate Spearman's correlation coefficient and p-value
corr, pval = spearmanr(x, y)
 
# print the result
print("Spearman's correlation coefficient:", corr)
print("p-value:", pval)

Spearman's correlation coefficient: 0.8026843318762265
p-value: 3.5285355183478057e-14

In [9]:
# Correlation between accuracy and completeness 

CrosstabResult=pd.crosstab(index=df['Accuracy (1-6): Rating1'],columns=df['Completeness(1-3): Rating1'])
# print(CrosstabResult)
 
# importing the required function
from scipy.stats import chi2_contingency
 
# Performing Chi-sq test
ChiSqResult = chi2_contingency(CrosstabResult)
 
# P-Value is the Probability of H0 being True
# If P-Value < 0.05 then only we Accept the assumption(H0)
 
print('The p-value of the ChiSq Test is:', ChiSqResult[1])

The p-value of the ChiSq Test is: 1.5616819531922254e-07

In [10]:
df['Difficulty level'].value_counts()['Easy']

11

In [11]:
df['Difficulty level'].value_counts()['Moderate']

36

In [12]:
df['Difficulty level'].value_counts()['Hard']

11

In [13]:
x = ['Median','Mean','Mode','SD','IQR']
y = [('Easy','Accuracy'),('Easy','Completeness'),('Moderate','Accuracy'),('Moderate','Completeness'),('Hard','Accuracy'),('Hard','Completeness')]
row_list = x
col_list = pd.MultiIndex.from_tuples(y)

df_measure = pd.DataFrame('',row_list,col_list)
df_measure

           Easy              Moderate                  Hard
       Accuracy Completeness Accuracy Completeness Accuracy Completeness
Median
Mean
Mode
SD
IQR

In [14]:
#Easy - Accuracy ; Completeness Rating1
import statistics
easy_df = df[df['Difficulty level']=='Easy']
set1 = easy_df['Accuracy (1-6): Rating1']
set2 = easy_df['Completeness(1-3): Rating1']
easy_median_acc = easy_df['Accuracy (1-6): Rating1'].median()
easy_median_com = easy_df['Completeness(1-3): Rating1'].median()
easy_mean_acc = easy_df['Accuracy (1-6): Rating1'].mean()
easy_mean_com = easy_df['Completeness(1-3): Rating1'].mean()
easy_mode_acc = statistics.mode(set1)
easy_mode_com = statistics.mode(set2)
easy_std_acc = easy_df['Accuracy (1-6): Rating1'].std()
easy_std_com = easy_df['Completeness(1-3): Rating1'].std()
easy_acc_q3, easy_acc_q1 = np.percentile(easy_df['Accuracy (1-6): Rating1'], [75 ,25])
easy_iqr_acc = easy_acc_q3 - easy_acc_q1
easy_com_q3, easy_com_q1 = np.percentile(easy_df['Completeness(1-3): Rating1'], [75 ,25])
easy_iqr_com = easy_com_q3 - easy_com_q1

In [15]:
easy_df

,Sno,Difficulty level,Question,Actual Answer,ChatGPT Answer,Accuracy (1-6): Rating1,Completeness(1-3): Rating1
1,2,Easy,How many ISAs are normally implemented by a si...,One,A single microarchitecture typically implement...,6,3
3,4,Easy,There are 52 weeks in a year on the Gregorian ...,6 bits,The least number of bits needed to represent 5...,6,3
6,7,Easy,What is the largest positive number one can re...,Translating the binary representation to decim...,"In an 8-bit 2's complement code, the largest p...",6,3
21,22,Easy,The sum of a negative 2’s complement number an...,FALSE. This will not generate an overflow beca...,False._x000D_\n_x000D_\nThe sum of a negative ...,4,2
25,26,Easy,Compute 01010111 OR 11010111. Write your resul...,11010111,The bitwise OR operation between the binary nu...,6,3
26,27,Easy,Compute 101 OR 110. Write your results in binary.,111,The bitwise OR operation between the binary nu...,6,3
29,30,Easy,Compute NOT(1011) OR NOT(1100). Write your res...,0111,To compute the expression NOT(1011) OR NOT(110...,6,3
31,32,Easy,"Write the IEEE floating point representation, ...",11.11 ; 0 10000000 11100000000000000000000,...,4,3
39,40,Easy,Fill in the truth table for the equations give...,q12: 1 q22: 0 q13: 1 q23: 1 q14: 0 q24: 1,Q1 = NOT(A AND B)_x000D_\n_x000D_\nQ2 = NOT(NO...,2,2
47,48,Easy,Which addressing mode is used by the instructi...,Register,"The instruction ""0001 010 000 0 00 001"" uses t...",2,3
57,58,Easy,What does the following LC-3 program do?_x000D...,ABCDEFGHI,The given LC-3 program performs a loop that co...,5,2

In [16]:
#Moderate - Accuracy ; Completeness Rating1
moderate_df = df[df['Difficulty level']=='Moderate']
set1 = moderate_df['Accuracy (1-6): Rating1']
set2 = moderate_df['Completeness(1-3): Rating1']
moderate_median_acc = moderate_df['Accuracy (1-6): Rating1'].median()
moderate_median_com = moderate_df['Completeness(1-3): Rating1'].median()
moderate_mean_acc = moderate_df['Accuracy (1-6): Rating1'].mean()
moderate_mean_com = moderate_df['Completeness(1-3): Rating1'].mean()
moderate_mode_acc = statistics.mode(set1)
moderate_mode_com = statistics.mode(set2)
moderate_std_acc = moderate_df['Accuracy (1-6): Rating1'].std()
moderate_std_com = moderate_df['Completeness(1-3): Rating1'].std()
moderate_acc_q3, moderate_acc_q1 = np.percentile(moderate_df['Accuracy (1-6): Rating1'], [75 ,25])
moderate_iqr_acc = moderate_acc_q3 - moderate_acc_q1
moderate_com_q3, moderate_com_q1 = np.percentile(moderate_df['Completeness(1-3): Rating1'], [75 ,25])
moderate_iqr_com = moderate_com_q3 - moderate_com_q1

In [17]:
#Hard - Accuracy ; Completeness Rating1
hard_df = df[df['Difficulty level']=='Hard']
set1 = hard_df['Accuracy (1-6): Rating1']
set2 = hard_df['Completeness(1-3): Rating1']
hard_median_acc = hard_df['Accuracy (1-6): Rating1'].median()
hard_median_com = hard_df['Completeness(1-3): Rating1'].median()
hard_mean_acc = hard_df['Accuracy (1-6): Rating1'].mean()
hard_mean_com = hard_df['Completeness(1-3): Rating1'].mean()
hard_mode_acc = statistics.mode(set1)
hard_mode_com = statistics.mode(set2)
hard_std_acc = hard_df['Accuracy (1-6): Rating1'].std()
hard_std_com = hard_df['Completeness(1-3): Rating1'].std()
hard_acc_q3, hard_acc_q1 = np.percentile(hard_df['Accuracy (1-6): Rating1'], [75 ,25])
hard_iqr_acc = hard_acc_q3 - hard_acc_q1
hard_com_q3, hard_com_q1 = np.percentile(hard_df['Completeness(1-3): Rating1'], [75 ,25])
hard_iqr_com = hard_com_q3 - hard_com_q1

In [18]:
df_measure.loc["Median", ('Easy', 'Accuracy')]=easy_median_acc 
df_measure.loc["Median", ('Easy', 'Completeness')]=easy_median_com
df_measure.loc["Median", ('Moderate', 'Accuracy')]=moderate_median_acc
df_measure.loc["Median", ('Moderate', 'Completeness')]=moderate_median_com
df_measure.loc["Median", ('Hard', 'Accuracy')]=hard_median_acc
df_measure.loc["Median", ('Hard', 'Completeness')]=hard_median_com

df_measure.loc["Mean", ('Easy', 'Accuracy')]=round(easy_mean_acc, 2)
df_measure.loc["Mean", ('Easy', 'Completeness')]=round(easy_mean_com, 2)
df_measure.loc["Mean", ('Moderate', 'Accuracy')]= round(moderate_mean_acc, 2)
df_measure.loc["Mean", ('Moderate', 'Completeness')]= round(moderate_mean_com, 2)
df_measure.loc["Mean", ('Hard', 'Accuracy')]= round(hard_mean_acc, 2)
df_measure.loc["Mean", ('Hard', 'Completeness')]= round(hard_mean_com, 2)

df_measure.loc["Mode", ('Easy', 'Accuracy')]=easy_mode_acc
df_measure.loc["Mode", ('Easy', 'Completeness')]=easy_mode_com
df_measure.loc["Mode", ('Moderate', 'Accuracy')]=moderate_mode_acc
df_measure.loc["Mode", ('Moderate', 'Completeness')]=moderate_mode_com
df_measure.loc["Mode", ('Hard', 'Accuracy')]=hard_mode_acc
df_measure.loc["Mode", ('Hard', 'Completeness')]=hard_mode_com

df_measure.loc["SD", ('Easy', 'Accuracy')]= round(easy_std_acc, 2)
df_measure.loc["SD", ('Easy', 'Completeness')]= round(easy_std_com, 2)
df_measure.loc["SD", ('Moderate', 'Accuracy')]= round(moderate_std_acc, 2)
df_measure.loc["SD", ('Moderate', 'Completeness')]= round(moderate_std_com, 2)
df_measure.loc["SD", ('Hard', 'Accuracy')]= round(hard_std_acc, 2)
df_measure.loc["SD", ('Hard', 'Completeness')]= round(hard_std_com, 2)

df_measure.loc["IQR", ('Easy', 'Accuracy')]=easy_iqr_acc
df_measure.loc["IQR", ('Easy', 'Completeness')]=easy_iqr_com
df_measure.loc["IQR", ('Moderate', 'Accuracy')]=moderate_iqr_acc
df_measure.loc["IQR", ('Moderate', 'Completeness')]=moderate_iqr_com
df_measure.loc["IQR", ('Hard', 'Accuracy')]=hard_iqr_acc
df_measure.loc["IQR", ('Hard', 'Completeness')]=hard_iqr_com

In [19]:
df_measure

           Easy              Moderate                  Hard
       Accuracy Completeness Accuracy Completeness Accuracy Completeness
Median      6.0          3.0      6.0          3.0      3.0          2.0
Mean       4.82         2.73     4.92         2.58     3.27         2.18
Mode          6            3        6            3        2            3
SD          1.6         0.47     1.66         0.81     1.42         0.87
IQR         2.0          0.5     2.25          0.0      2.0          1.5

In [27]:
# Kruskal-Wallis Test
from scipy import stats
 
# Defining data groups
data_group1 = easy_df['Accuracy (1-6): Rating1']
data_group2 = moderate_df['Accuracy (1-6): Rating1']
data_group3 = hard_df['Accuracy (1-6): Rating1']
 
# Conduct the Kruskal-Wallis Test
result = stats.kruskal(data_group1,data_group2,data_group3)
 
# Print the result
print(result)

KruskalResult(statistic=8.910127025879914, pvalue=0.011619581857389533)

In [28]:
# code for Mann-Whitney U test
from scipy.stats import mannwhitneyu
# Take batch 1 and batch 2 data as per above example
batch_1 = easy_df['Accuracy (1-6): Rating1']
batch_2 = moderate_df['Accuracy (1-6): Rating1']
  
# perform mann whitney test
stat, p_value = mannwhitneyu(batch_1, batch_2)
print('Statistics=%.2f, p=%.2f' % (stat, p_value))
# Level of significance
alpha = 0.05
# conclusion
if p_value < alpha:
    print('Reject Null Hypothesis (Significant difference between two samples)')
else:
    print('Do not Reject Null Hypothesis (No significant difference between two samples)')

Statistics=182.50, p=0.66
Do not Reject Null Hypothesis (No significant difference between two samples)

In [29]:
from scipy.stats import mannwhitneyu
# Take batch 1 and batch 2 data as per above example
batch_1 = moderate_df['Accuracy (1-6): Rating1']
batch_2 = hard_df['Accuracy (1-6): Rating1']
  
# perform mann whitney test
stat, p_value = mannwhitneyu(batch_1, batch_2)
print('Statistics=%.2f, p=%.5f' % (stat, p_value))
# Level of significance
alpha = 0.05
# conclusion
if p_value < alpha:
    print('Reject Null Hypothesis (Significant difference between two samples)')
else:
    print('Do not Reject Null Hypothesis (No significant difference between two samples)')

Statistics=303.00, p=0.00405
Reject Null Hypothesis (Significant difference between two samples)

In [30]:
from scipy.stats import mannwhitneyu
# Take batch 1 and batch 2 data as per above example
batch_1 = hard_df['Accuracy (1-6): Rating1']
batch_2 = easy_df['Accuracy (1-6): Rating1']
  
# perform mann whitney test
stat, p_value = mannwhitneyu(batch_1, batch_2)
print('Statistics=%.2f, p=%.2f' % (stat, p_value))
# Level of significance
alpha = 0.05
# conclusion
if p_value < alpha:
    print('Reject Null Hypothesis (Significant difference between two samples)')
else:
    print('Do not Reject Null Hypothesis (No significant difference between two samples)')

Statistics=29.00, p=0.04
Reject Null Hypothesis (Significant difference between two samples)